---
- name: Copy file with owner and permissions
  become: true
  hosts: all

  tasks:

    - name: Example copying file with owner and permissions
      copy:
        src: /Jenkins/project/Dockerfile
        dest: /Jenkins/project/
        owner: ec2-user
        group: ec2-user
        mode: '0777'